# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalbeltexam', '0002_auto_20170324_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='finalbeltexam.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
